# name of the  Workflow (appears in the actions tab)
name: hello-world workflow

on:
  # name of the event that triggers the workflow
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  # name of the job
  greet:
    # name of the runner
    runs-on: ubuntu-latest
    steps:
      # name of the step
      - name: Print Hello World
        # the action to run
        run: echo "Hello World"
  
    